LIB: CLI: add bind_info, bind and unbind functions
lsgunth/switchtec-user pull request #2
Opened 2018-03-04 14:42 UTC by glimchb

2018-03-05 18:14 UTC, lsgunth commented
Thanks, this largely looks great but it needs to be rebased off of master seeing the first commit is already in master. I also have a number of minor nits with the code which I'll comment on in the patch.

I'd also really like to see a better commit description describing what bind/unbind do.

2018-03-05 18:33 UTC, lsgunth requested changes
Largely this looks good and I'd love to see it merged but I'd really appreciate it if you can fix all the style issues.

I also noticed you have set the execute bits (100644->100755) on a couple of files. Please do not do that and remove that change from your patch.

Thanks

Logan

2018-03-05 18:33 UTC, lsgunth commented on cli/main.c
> +
Please don't use multiple blank lines. One is sufficient. (This follows Linux Kernel coding convention). There are a couple cases below of this too please fix them all.

2018-03-05 18:33 UTC, lsgunth commented on cli/main.c
> +	printf("physical port %u binded to %u, partition %u\n", bind_status.phys_port_id,
The past tense of "bind" should be "bound" not "binded"

2018-03-05 18:33 UTC, lsgunth commented on cli/main.c
> +	const char *desc = "Bind switchtech PCI2PCI logical port to physical port";
s/switchtech/switchtec/ 

Also what is meant by PCI2PCI?

2018-03-05 18:33 UTC, lsgunth commented on cli/main.c
> +	const char *desc = "Unbind switchtech PCI2PCI logical port from physical port";
Same as above

2018-03-05 18:33 UTC, lsgunth commented on cli/main.c
> +	CMD(port_bind, "Binds switchtec logical and physical ports"),
s/Binds/Bind/

2018-03-05 18:33 UTC, lsgunth commented on cli/main.c
> +	CMD(port_unbind, "Unbinds switchtec logical port from physical port"),
s/Unbinds/Unbind/

2018-03-05 18:33 UTC, lsgunth commented on inc/switchtec/registers.h
> +struct switchtec_bind_status_in {
These definitions do not belong in registers.h as they are not GAS registers.

Either put them in switchtec.c along with the functions that use them or if you think there's value in exposing them to the user put them in their own bind.h similar to pmon.h

2018-03-05 18:33 UTC, lsgunth commented on inc/switchtec/switchtec.h
> +int switchtec_bind_info(struct switchtec_dev *dev, struct switchtec_bind_status_out *bind_status, int phy_port);
Max line length is 80 chars. These lines are too long and should be wrapped and indented just like the other functions in this file. (Per Kernel Style)

2018-03-05 18:33 UTC, lsgunth commented on lib/switchtec.c
> +int switchtec_bind_info(struct switchtec_dev *dev, struct switchtec_bind_status_out *bind_status, int phy_port )
Line is too long

2018-03-05 18:33 UTC, lsgunth commented on lib/switchtec.c
> +	  .phys_port_id = phy_port
That open brace { should be on the previous line. Please follow the style in the rest of the code.

2018-03-05 18:33 UTC, lsgunth commented on lib/switchtec.c
> +	{ .sub_cmd = MRPC_PORT_BIND,
Same as above

2018-03-06 07:26 UTC, glimchb commented
Thanks for the comments. Will be working on fixing them

--
Best regards, Boris
Let me google that for you<http://lmgtfy.com/>

From: Logan Gunthorpe [mailto:notifications@github.com]
Sent: Monday, March 5, 2018 20:18
To: lsgunth/switchtec-user <switchtec-user@noreply.github.com>
Cc: Glimcher, Boris <Boris.Glimcher@emc.com>; Author <author@noreply.github.com>
Subject: Re: [lsgunth/switchtec-user] LIB: CLI: add bind_info, bind and unbind functions (#2)


Thanks, this largely looks great but it needs to be rebased off of master seeing the first commit is already in master. I also have a number of minor nits with the code which I'll comment on in the patch.

I'd also really like to see a better commit description describing what bind/unbind do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/lsgunth/switchtec-user/pull/2#issuecomment-370511582>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AjB92UUrTGKpYUV_zUYOyt_cxlPO1kwSks5tbYCLgaJpZM4SbWus>.

2018-03-07 14:12 UTC, glimchb commented
done

2018-03-07 21:15 UTC, lsgunth commented
Many thanks. I cleaned up a couple more minor style commits and merged it into Microsemi/devel.

Logan

2018-03-07 21:15 UTC, closed without merging